add test report step

diff --git a/.github/workflows/workflows.yml b/.github/workflows/workflows.yml
--- a/.github/workflows/workflows.yml
+++ b/.github/workflows/workflows.yml
@@ -10,11 +10,17 @@ jobs:
         run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DBUILD_UNIT_TESTS="True"
 
       - name: Build
-        run: cmake --build ${{github.workspace}}/build --config Debug
+        run: cmake --build ${{github.workspace}}/build --config Debug --junit-report ./test-result.xml
 
       - name: Test
         working-directory: ${{github.workspace}}/build/src/test
         run: ls -alh && ctest -C Debug
+
+      - name: Test Report
+        uses: mikepenz/action-junit-report@v5
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '${{github.workspace}}/build/src/test/test-result.xml'
 
   run:
     runs-on: ubuntu-latest
